AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for daily-numbers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: ruby2.5
Parameters:
  Version:
    Type: String
    Default: v1

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: DailyNumbers
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      CallbackURLs:
      - https://www.fryolator.com/
      GenerateSecret: false
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH
  # How to generate a Cognito User Pool

  UserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      Username: john@fnnny.com
      UserPoolId: !Ref UserPool

  MetricSnapshotsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MetricsSnapshotsTable

  GetMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda to CRUD numbers
      Runtime: ruby2.5
      Timeout: 5
      Handler: app.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaFullAccess
      CodeUri: lambdas/get_all
      Layers:
        - arn:aws:lambda:us-west-2:402153944964:layer:metrics-bundle-layer:1
      Events:
        GetMetrics:
          Type: Api
          Properties:
            Path: /numbers
            Method: GET
        ScheduledGetMetrics:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda to send numbers email
      Runtime: ruby2.5
      Timeout: 10
      Handler: app.lambda_handler
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSESFullAccess
      - AmazonCognitoPowerUser
      CodeUri: lambdas/send_email
      # Layers:
      #   - arn:aws:lambda:us-west-2:402153944964:layer:metrics-bundle-layer:1
      Events:
        GetMetrics:
          Type: Api
          Properties:
            Path: /send
            Method: GET

  # EmailSqsQueue:
  #     Type: AWS::SQS::Queue

    # Couldn't get this working, just uploaded layer to console
    # MetricsBundleLayer:
    #   # Type: AWS::Serverless::LayerVersion
    #   Type: AWS::Lambda::LayerVersion
    #   Properties:
    #     LayerName: metrics-bundle-layer
    #     Description: Bundled gems for daily numbers
    #     ContentUri: dependencies/
    #     CompatibleRuntimes:
    #       - ruby2.5
    #     LicenseInfo: MIT
    #     RetentionPolicy: Retain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MetricsApi:
    Description: "API Gateway endpoint URL for Prod stage for GetMetricsFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/numbers"
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
